{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "filestash.fullname" . }}
  labels:
    {{- include "filestash.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: {{ .Values.persistence.size }}
{{- end -}}